"""Seed market-data for the skill catalog.

This is heuristic reference data, not a live feed. See README 'Ideas to
extend this' for how to swap it for a real data source (freelance-platform
APIs, job-board scrapes, a scheduled refresh job, etc).
"""
from . import db
from .models import SkillCatalog

SEED = [
    dict(name="JavaScript", category="Programming & Tech", demand=9, hourly_low=25, hourly_high=75,
         platforms="Upwork,Toptal,Contra", trend="rising",
         product_idea="Boilerplate kits / paid components", pairs="Web Development,TypeScript,React"),
    dict(name="Python", category="Programming & Tech", demand=9, hourly_low=25, hourly_high=80,
         platforms="Upwork,Toptal,Fiverr", trend="rising",
         product_idea="Automation scripts / templates", pairs="Data Analysis,Machine Learning,Automation"),
    dict(name="Web Development", category="Programming & Tech", demand=9, hourly_low=20, hourly_high=70,
         platforms="Upwork,Fiverr,Contra", trend="rising",
         product_idea="Website templates / starter kits", pairs="JavaScript,UI/UX Design,WordPress"),
    dict(name="Mobile App Development", category="Programming & Tech", demand=8, hourly_low=30, hourly_high=85,
         platforms="Toptal,Upwork", trend="rising",
         product_idea="App source-code templates", pairs="UI/UX Design,JavaScript"),
    dict(name="Data Analysis", category="Programming & Tech", demand=8, hourly_low=25, hourly_high=65,
         platforms="Upwork,Toptal,Kolabtree", trend="rising",
         product_idea="Dashboard templates", pairs="Python,Machine Learning,Excel"),
    dict(name="Machine Learning", category="Programming & Tech", demand=8, hourly_low=35, hourly_high=95,
         platforms="Toptal,Upwork", trend="rising",
         product_idea="Pretrained model tools", pairs="Python,Data Analysis"),
    dict(name="UI/UX Design", category="Programming & Tech", demand=8, hourly_low=25, hourly_high=70,
         platforms="Upwork,Dribbble,Contra", trend="rising",
         product_idea="UI kits / Figma templates", pairs="Graphic Design,Web Development"),
    dict(name="WordPress", category="Programming & Tech", demand=6, hourly_low=15, hourly_high=45,
         platforms="Fiverr,Upwork", trend="stable",
         product_idea="Custom themes / plugins", pairs="Web Development,SEO"),
    dict(name="SEO", category="Marketing & Business", demand=7, hourly_low=20, hourly_high=55,
         platforms="Upwork,Fiverr", trend="stable",
         product_idea="SEO audit templates", pairs="Content Writing,Digital Marketing"),
    dict(name="Cybersecurity", category="Programming & Tech", demand=8, hourly_low=35, hourly_high=100,
         platforms="Toptal,Upwork", trend="rising",
         product_idea="Security checklists / audits", pairs="Python,Networking"),
    dict(name="Excel", category="Programming & Tech", demand=6, hourly_low=15, hourly_high=40,
         platforms="Fiverr,Upwork", trend="stable",
         product_idea="Spreadsheet templates", pairs="Data Analysis,Bookkeeping"),
    dict(name="Graphic Design", category="Design & Creative", demand=7, hourly_low=15, hourly_high=50,
         platforms="Fiverr,99designs,Dribbble", trend="stable",
         product_idea="Design template packs", pairs="Illustration,UI/UX Design"),
    dict(name="Video Editing", category="Design & Creative", demand=8, hourly_low=15, hourly_high=55,
         platforms="Fiverr,Upwork", trend="rising",
         product_idea="Editing presets / LUTs", pairs="Photography,Animation"),
    dict(name="Photography", category="Design & Creative", demand=5, hourly_low=20, hourly_high=60,
         platforms="Fiverr,local clients", trend="stable",
         product_idea="Stock photo packs / presets", pairs="Video Editing,Graphic Design"),
    dict(name="Illustration", category="Design & Creative", demand=6, hourly_low=15, hourly_high=50,
         platforms="Fiverr,Dribbble", trend="stable",
         product_idea="Illustration/sticker packs", pairs="Graphic Design,Animation"),
    dict(name="Animation", category="Design & Creative", demand=7, hourly_low=20, hourly_high=65,
         platforms="Fiverr,Upwork", trend="rising",
         product_idea="Motion graphic templates", pairs="Video Editing,Illustration"),
    dict(name="3D Modeling", category="Design & Creative", demand=7, hourly_low=20, hourly_high=70,
         platforms="Upwork,ArtStation", trend="rising",
         product_idea="3D asset packs", pairs="Animation,Illustration"),
    dict(name="Copywriting", category="Writing & Content", demand=7, hourly_low=20, hourly_high=60,
         platforms="Upwork,Contra", trend="stable",
         product_idea="Swipe files / prompt packs", pairs="Digital Marketing,Content Writing"),
    dict(name="Content Writing", category="Writing & Content", demand=6, hourly_low=12, hourly_high=45,
         platforms="Upwork,Fiverr", trend="stable",
         product_idea="Content templates / courses", pairs="SEO,Copywriting"),
    dict(name="Technical Writing", category="Writing & Content", demand=7, hourly_low=20, hourly_high=55,
         platforms="Upwork,Contra", trend="stable",
         product_idea="Documentation templates", pairs="Editing/Proofreading,Programming"),
    dict(name="Translation", category="Writing & Content", demand=5, hourly_low=15, hourly_high=40,
         platforms="ProZ,Upwork,Fiverr", trend="stable",
         product_idea="Glossary/phrase packs", pairs="Content Writing"),
    dict(name="Editing/Proofreading", category="Writing & Content", demand=5, hourly_low=12, hourly_high=38,
         platforms="Upwork,Fiverr,Reedsy", trend="stable",
         product_idea="Style-guide templates", pairs="Content Writing,Technical Writing"),
    dict(name="Digital Marketing", category="Marketing & Business", demand=7, hourly_low=18, hourly_high=55,
         platforms="Upwork,Fiverr", trend="rising",
         product_idea="Ad-campaign templates", pairs="Social Media Management,SEO"),
    dict(name="Social Media Management", category="Marketing & Business", demand=6, hourly_low=12, hourly_high=40,
         platforms="Fiverr,Upwork", trend="stable",
         product_idea="Content calendar templates", pairs="Digital Marketing,Graphic Design"),
    dict(name="Email Marketing", category="Marketing & Business", demand=6, hourly_low=15, hourly_high=45,
         platforms="Upwork,Fiverr", trend="stable",
         product_idea="Email sequence templates", pairs="Copywriting,Digital Marketing"),
    dict(name="Sales", category="Marketing & Business", demand=6, hourly_low=15, hourly_high=50,
         platforms="Upwork,direct clients", trend="stable",
         product_idea="Sales script templates", pairs="Business Consulting"),
    dict(name="Business Consulting", category="Marketing & Business", demand=7, hourly_low=30, hourly_high=90,
         platforms="Toptal,Catalant", trend="stable",
         product_idea="Strategy frameworks / templates", pairs="Project Management,Sales"),
    dict(name="Project Management", category="Marketing & Business", demand=6, hourly_low=20, hourly_high=55,
         platforms="Upwork,Toptal", trend="stable",
         product_idea="PM templates / trackers", pairs="Business Consulting"),
    dict(name="Online Tutoring", category="Teaching & Coaching", demand=6, hourly_low=15, hourly_high=45,
         platforms="Preply,Wyzant,Outschool", trend="rising",
         product_idea="Mini-course / worksheet packs", pairs="Language Teaching"),
    dict(name="Language Teaching", category="Teaching & Coaching", demand=6, hourly_low=12, hourly_high=35,
         platforms="Preply,italki", trend="stable",
         product_idea="Language learning guides", pairs="Online Tutoring,Translation"),
    dict(name="Fitness Coaching", category="Teaching & Coaching", demand=5, hourly_low=15, hourly_high=50,
         platforms="Trainerize,local clients", trend="stable",
         product_idea="Training plan templates", pairs="Nutrition Coaching"),
    dict(name="Career Coaching", category="Teaching & Coaching", demand=5, hourly_low=25, hourly_high=70,
         platforms="direct clients,Coach.me", trend="rising",
         product_idea="Resume/interview templates", pairs="Business Consulting"),
    dict(name="Voice Over", category="Audio & Music", demand=5, hourly_low=20, hourly_high=60,
         platforms="Voices.com,Fiverr", trend="stable",
         product_idea="Voice sample libraries", pairs="Podcast Editing"),
    dict(name="Music Production", category="Audio & Music", demand=5, hourly_low=20, hourly_high=60,
         platforms="SoundBetter,Fiverr", trend="stable",
         product_idea="Sample packs / beats", pairs="Podcast Editing"),
    dict(name="Podcast Editing", category="Audio & Music", demand=6, hourly_low=15, hourly_high=45,
         platforms="Fiverr,Upwork", trend="rising",
         product_idea="Podcast production templates", pairs="Voice Over,Music Production"),
    dict(name="Bookkeeping", category="Trades & Other", demand=6, hourly_low=15, hourly_high=40,
         platforms="Upwork,Bench,local clients", trend="stable",
         product_idea="Bookkeeping templates", pairs="Excel"),
    dict(name="Virtual Assistance", category="Trades & Other", demand=6, hourly_low=10, hourly_high=30,
         platforms="Upwork,Fiverr,Belay", trend="stable",
         product_idea="SOP / workflow templates", pairs="Project Management"),
    dict(name="Data Entry", category="Trades & Other", demand=3, hourly_low=8, hourly_high=20,
         platforms="Upwork,Fiverr", trend="declining",
         product_idea="Data cleaning macros", pairs="Excel,Virtual Assistance"),
    dict(name="Craft/Handmade Goods", category="Trades & Other", demand=4, hourly_low=10, hourly_high=35,
         platforms="Etsy,local markets", trend="stable",
         product_idea="Digital patterns / templates", pairs="Illustration"),
]


def seed_catalog():
    """Populate the skill_catalog table once, if it's empty."""
    if SkillCatalog.query.first() is not None:
        return
    for row in SEED:
        db.session.add(SkillCatalog(**row))
    db.session.commit()
